/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * SIERCP — Firestore ↔ Legacy Course Bridge
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * This adapter converts data from the new Firestore-based course_templates and
 * cohorts into the legacy Curso/Grupo format used by existing pages like
 * /formacion/[slug] and /checkout.
 *
 * This allows the frontend to read from Firestore dynamically while
 * maintaining 100% backward compatibility with existing components.
 *
 * Once all pages are migrated to use CourseTemplate/Cohort directly,
 * this bridge can be removed.
 */

import type { Curso, Grupo } from '@/data/cursos';

// ─── API Response Types ──────────────────────────────────────────────────────

interface APICohort {
  id: string;
  templateId: string;
  courseSlug: string;
  courseTitle: string;
  cohortNumber: number;
  scheduleLabel: string;
  enrollmentStart: string;
  enrollmentEnd: string;
  classesStart: string;
  maxStudents: number;
  enrolledCount: number;
  priceCOP: number;
  priceUSD: number;
  status: string;
  isAutoGenerated: boolean;
}

interface APICourseTemplate {
  id: string;
  slug: string;
  title: string;
  description: string;
  descriptionLong: string;
  level: string;
  modality: string;
  duration: string;
  sessions: number;
  priceCOP: number;
  priceUSD: number;
  objectives: string[];
  requirements: string[];
  includesCertificate: boolean;
  regulations: string[];
  tags: string[];
  icon: string;
  targetAudience: string;
  modules: Array<{ title: string; topics: string[]; duration: string; order: number }>;
  institutionId: string;
  institutionName: string;
  isAutomated: boolean;
  cohorts: APICohort[];
  availableSlots: number;
}

// ─── Converters ──────────────────────────────────────────────────────────────

function cohortToGrupo(cohort: APICohort): Grupo {
  const statusMap: Record<string, Grupo['estado']> = {
    UPCOMING: 'proximo',
    OPEN: 'abierto',
    FULL: 'agotado',
    IN_PROGRESS: 'en_curso',
    CLOSED: 'finalizado',
    COMPLETED: 'finalizado',
  };

  /* Deriva el turno a partir de la etiqueta de horario cuando esté disponible */
  const horario: 'mañana' | 'tarde' =
    (cohort.scheduleLabel ?? '').toLowerCase().includes('mañana') ? 'mañana' : 'tarde';

  return {
    id: cohort.id,
    horario,
    horarioLabel: cohort.scheduleLabel,
    inscripcionInicio: new Date(cohort.enrollmentStart),
    inscripcionFin: new Date(cohort.enrollmentEnd),
    inicioClases: new Date(cohort.classesStart),
    maxEstudiantes: cohort.maxStudents,
    inscritos: cohort.enrolledCount,
    estado: statusMap[cohort.status] || 'proximo',
  };
}

function templateToCurso(template: APICourseTemplate): Curso {
  return {
    slug: template.slug,
    nombre: template.title,
    descripcion: template.description,
    descripcionLarga: template.descriptionLong,
    nivel: template.level as Curso['nivel'],
    modalidad: template.modality as Curso['modalidad'],
    duracion: template.duration,
    sesiones: template.sessions,
    precioCOP: template.priceCOP,
    precioUSD: template.priceUSD,
    objetivos: template.objectives,
    requisitos: template.requirements,
    incluyeCertificado: template.includesCertificate,
    normativa: template.regulations,
    tags: template.tags,
    icono: template.icon,
    paraQuien: template.targetAudience,
    modulos: template.modules.map((m) => ({
      nombre: m.title,
      temas: m.topics,
      duracion: m.duration,
    })),
    grupos: (template.cohorts || []).map(cohortToGrupo),
  };
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Fetches all courses from the API and converts them to legacy Curso format.
 * Falls back to hardcoded data if the API is unavailable.
 */
export async function fetchCursosFromFirestore(institutionId?: string): Promise<Curso[]> {
  try {
    const params = new URLSearchParams();
    if (institutionId) params.set('institution', institutionId);

    const res = await fetch(`/api/courses?${params.toString()}`);
    if (!res.ok) throw new Error(`API error: ${res.status}`);

    const data = await res.json();
    return (data.courses || []).map(templateToCurso);
  } catch (err) {
    console.warn('[Bridge] API unavailable, falling back to static data:', err);
    // Fallback to the hardcoded cursos.ts
    const { cursos } = await import('@/data/cursos');
    return cursos;
  }
}

/**
 * Fetches a single course by slug from the API.
 */
export async function fetchCursoBySlug(slug: string, institutionId?: string): Promise<Curso | null> {
  try {
    const params = new URLSearchParams({ slug });
    if (institutionId) params.set('institution', institutionId);

    const res = await fetch(`/api/courses?${params.toString()}`);
    if (!res.ok) throw new Error(`API error: ${res.status}`);

    const data = await res.json();
    const courses = (data.courses || []).map(templateToCurso);
    return courses[0] || null;
  } catch (err) {
    console.warn('[Bridge] Falling back to static data for slug:', slug);
    const { getCursoBySlug } = await import('@/data/cursos');
    return getCursoBySlug(slug) || null;
  }
}

/**
 * Fetches the raw API data (templates + cohorts) for advanced usage.
 */
export async function fetchRawCatalog(institutionId?: string): Promise<APICourseTemplate[]> {
  const params = new URLSearchParams();
  if (institutionId) params.set('institution', institutionId);

  const res = await fetch(`/api/courses?${params.toString()}`);
  if (!res.ok) throw new Error(`API error: ${res.status}`);

  const data = await res.json();
  return data.courses || [];
}

/**
 * Gets the cohort metadata needed for enrollment.
 * This is the data that needs to be sent to /api/enrollment.
 */
export function getEnrollmentPayload(
  curso: Curso,
  grupoId: string,
  rawCatalog: APICourseTemplate[],
) {
  const template = rawCatalog.find((t) => t.slug === curso.slug);
  const cohort = template?.cohorts?.find((c) => c.id === grupoId);

  return {
    cohortId: grupoId,
    templateId: template?.id || '',
    institutionId: template?.institutionId || 'jomar-seguridad',
    cursoSlug: curso.slug,
  };
}
