'use client';

import { useEffect, useState, use } from 'react';
import { useRouter } from 'next/navigation';
import { Header } from '@/components/layout/header';
import { PageHero } from '@/components/ui/page-hero';
import {
  Users, Calendar, Clock, Plus, ChevronLeft,
  Zap, DollarSign, RefreshCw, Lock, Unlock,
  CheckCircle2, AlertCircle, TrendingUp, Hash
} from 'lucide-react';
import toast from 'react-hot-toast';

interface CohortData {
  id: string;
  cohortNumber: number;
  scheduleLabel: string;
  enrollmentStart: string;
  enrollmentEnd: string;
  classesStart: string;
  maxStudents: number;
  enrolledCount: number;
  priceCOP: number;
  status: string;
  isAutoGenerated: boolean;
}

interface TemplateData {
  id: string;
  slug: string;
  title: string;
  description: string;
  level: string;
  duration: string;
  sessions: number;
  priceCOP: number;
  priceUSD: number;
  isAutomated: boolean;
  modules: any[];
}

async function getIdToken(): Promise<string> {
  const { getAuth } = await import('firebase/auth');
  const auth = getAuth();
  if (!auth.currentUser) throw new Error('No autenticado');
  return auth.currentUser.getIdToken();
}

const STATUS_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  UPCOMING: { label: 'Próximo', color: '#6366F1', bg: '#EEF2FF' },
  OPEN: { label: 'Abierto', color: '#10B981', bg: '#DCFCE7' },
  FULL: { label: 'Agotado', color: '#F59E0B', bg: '#FEF3C7' },
  IN_PROGRESS: { label: 'En Curso', color: '#3B82F6', bg: '#DBEAFE' },
  CLOSED: { label: 'Cerrado', color: '#6B7280', bg: '#F3F4F6' },
  COMPLETED: { label: 'Finalizado', color: '#8B5CF6', bg: '#F5F3FF' },
};

export default function CourseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const [template, setTemplate] = useState<TemplateData | null>(null);
  const [cohorts, setCohorts] = useState<CohortData[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);

  const fetchData = async () => {
    try {
      setLoading(true);
      const idToken = await getIdToken();

      // Fetch all templates and find this one
      const templatesRes = await fetch('/api/admin/courses', {
        headers: { Authorization: `Bearer ${idToken}` },
      });
      const templatesData = await templatesRes.json();
      const tmpl = (templatesData.templates || []).find((t: any) => t.id === id);
      setTemplate(tmpl || null);

      // Fetch cohorts for this template
      const cohortsRes = await fetch(`/api/admin/cohorts?templateId=${id}`, {
        headers: { Authorization: `Bearer ${idToken}` },
      });
      const cohortsData = await cohortsRes.json();
      setCohorts(cohortsData.cohorts || []);
    } catch (err) {
      console.error('Error:', err);
      toast.error('Error al cargar el curso');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, [id]);

  const createCohort = async () => {
    if (!template) return;
    setCreating(true);
    try {
      const idToken = await getIdToken();
      const res = await fetch('/api/admin/cohorts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
        body: JSON.stringify({
          templateId: id,
          scheduleLabel: 'Nuevo Horario',
          maxStudents: 30,
        }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success(data.message);
        fetchData();
      } else {
        toast.error(data.error || 'Error al crear grupo');
      }
    } catch (err) {
      toast.error('Error de conexión');
    } finally {
      setCreating(false);
    }
  };

  const closeCohort = async (cohortId: string) => {
    try {
      const idToken = await getIdToken();
      const res = await fetch('/api/admin/cohorts', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
        body: JSON.stringify({ id: cohortId, status: 'CLOSED' }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success('Grupo cerrado');
        fetchData();
      }
    } catch (err) {
      toast.error('Error al cerrar grupo');
    }
  };

  const totalEnrolled = cohorts.reduce((s, c) => s + (c.enrolledCount || 0), 0);
  const openCohorts = cohorts.filter((c) => c.status === 'OPEN');
  const totalCapacity = cohorts.filter(c => ['OPEN', 'UPCOMING'].includes(c.status))
    .reduce((s, c) => s + c.maxStudents, 0);

  const formatDate = (iso: string) => {
    if (!iso) return '—';
    return new Date(iso).toLocaleDateString('es-CO', { day: 'numeric', month: 'short', year: 'numeric' });
  };

  const formatCOP = (n: number) =>
    new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(n);

  if (loading) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: '#F8FAFC' }}>
        <Header title="Cargando..." />
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#94A3B8' }}>
          Cargando curso...
        </div>
      </div>
    );
  }

  if (!template) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: '#F8FAFC' }}>
        <Header title="Curso no encontrado" />
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <button onClick={() => router.back()} style={{ padding: '12px 24px', borderRadius: 12, background: '#1800AD', color: '#fff', border: 'none', cursor: 'pointer', fontWeight: 700 }}>
            <ChevronLeft size={16} /> Volver
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: '#F8FAFC' }}>
      <Header title={`${template.title} — Gestión de Grupos`} />

      <div style={{ flex: 1, padding: '32px', overflowY: 'auto' }}>
        <PageHero
          title={template.title}
          subtitle={`${template.duration} · ${template.sessions} sesiones · ${template.level} · ${template.isAutomated ? '⚡ Automatizado' : '✏️ Manual'}`}
          parentTitle="Cursos"
          parentHref="/admin/platform-courses"
          actions={
            !template.isAutomated ? (
              <button
                onClick={createCohort}
                disabled={creating}
                style={{
                  padding: '10px 20px', borderRadius: 12, background: '#1800AD', color: '#fff',
                  border: 'none', fontSize: 13, fontWeight: 700, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', gap: 8, opacity: creating ? 0.6 : 1,
                }}
              >
                <Plus size={16} /> {creating ? 'Creando...' : 'Nuevo Grupo'}
              </button>
            ) : (
              <div style={{
                padding: '10px 16px', borderRadius: 12, background: '#EEF2FF', color: '#4338CA',
                fontSize: 12, fontWeight: 800, display: 'flex', alignItems: 'center', gap: 6,
              }}>
                <Zap size={14} /> Los grupos se generan automáticamente
              </div>
            )
          }
        />

        {/* Stats */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 24 }}>
          {[
            { label: 'Total Inscritos', value: totalEnrolled, icon: Users, color: '#1800AD' },
            { label: 'Grupos Abiertos', value: openCohorts.length, icon: Unlock, color: '#10B981' },
            { label: 'Capacidad Total', value: totalCapacity, icon: TrendingUp, color: '#F59E0B' },
            { label: 'Precio', value: formatCOP(template.priceCOP), icon: DollarSign, color: '#6366F1' },
          ].map((s, i) => (
            <div key={i} style={{
              background: '#fff', border: '1px solid #E2E8F0', borderRadius: 16,
              padding: '16px 20px', display: 'flex', alignItems: 'center', gap: 14,
            }}>
              <div style={{
                width: 40, height: 40, borderRadius: 10, background: `${s.color}10`,
                display: 'flex', alignItems: 'center', justifyContent: 'center', color: s.color,
              }}>
                <s.icon size={20} />
              </div>
              <div>
                <div style={{ fontSize: 11, color: '#94A3B8', fontWeight: 700 }}>{s.label}</div>
                <div style={{ fontSize: 20, fontWeight: 800, color: '#0F172A' }}>{s.value}</div>
              </div>
            </div>
          ))}
        </div>

        {/* Cohorts Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 16 }}>
          {cohorts.map((cohort) => {
            const cfg = STATUS_CONFIG[cohort.status] || STATUS_CONFIG.CLOSED;
            const pct = cohort.maxStudents > 0 ? Math.round((cohort.enrolledCount / cohort.maxStudents) * 100) : 0;
            return (
              <div key={cohort.id} style={{
                background: '#fff', border: '1px solid #E2E8F0', borderRadius: 20, padding: 24,
                boxShadow: '0 1px 3px rgba(0,0,0,0.05)', transition: 'all 0.2s',
              }}>
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <div style={{
                      width: 36, height: 36, borderRadius: 10, background: cfg.bg,
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                    }}>
                      <Hash size={16} style={{ color: cfg.color }} />
                    </div>
                    <div>
                      <div style={{ fontWeight: 800, color: '#0F172A', fontSize: 16 }}>
                        Grupo #{cohort.cohortNumber}
                      </div>
                      <div style={{ fontSize: 11, color: '#94A3B8', fontWeight: 600 }}>
                        {cohort.scheduleLabel}
                      </div>
                    </div>
                  </div>
                  <span style={{
                    fontSize: 9, fontWeight: 900, padding: '4px 10px', borderRadius: 20,
                    background: cfg.bg, color: cfg.color, letterSpacing: '0.05em',
                  }}>
                    {cfg.label.toUpperCase()}
                  </span>
                </div>

                {/* Progress bar */}
                <div style={{ marginBottom: 16 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
                    <span style={{ fontSize: 12, color: '#64748B', fontWeight: 600 }}>Cupos</span>
                    <span style={{ fontSize: 12, fontWeight: 800, color: '#0F172A' }}>
                      {cohort.enrolledCount}/{cohort.maxStudents}
                    </span>
                  </div>
                  <div style={{ height: 6, background: '#F1F5F9', borderRadius: 3 }}>
                    <div style={{
                      width: `${Math.min(pct, 100)}%`, height: '100%', borderRadius: 3,
                      background: pct >= 100 ? '#EF4444' : pct >= 75 ? '#F59E0B' : '#10B981',
                      transition: 'width 0.5s ease',
                    }} />
                  </div>
                </div>

                {/* Dates */}
                <div style={{ display: 'grid', gap: 8, marginBottom: 16 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
                    <span style={{ color: '#94A3B8', display: 'flex', alignItems: 'center', gap: 4 }}>
                      <Calendar size={12} /> Inscripción
                    </span>
                    <span style={{ color: '#475569', fontWeight: 600 }}>
                      {formatDate(cohort.enrollmentStart)} — {formatDate(cohort.enrollmentEnd)}
                    </span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
                    <span style={{ color: '#94A3B8', display: 'flex', alignItems: 'center', gap: 4 }}>
                      <Clock size={12} /> Inicio clases
                    </span>
                    <span style={{ color: '#475569', fontWeight: 600 }}>{formatDate(cohort.classesStart)}</span>
                  </div>
                </div>

                {/* Auto-generated badge */}
                {cohort.isAutoGenerated && (
                  <div style={{
                    display: 'flex', alignItems: 'center', gap: 6, padding: '6px 10px',
                    background: '#EEF2FF', borderRadius: 8, marginBottom: 12,
                    fontSize: 10, fontWeight: 700, color: '#4338CA',
                  }}>
                    <Zap size={12} /> Generado automáticamente por el sistema
                  </div>
                )}

                {/* Actions */}
                {cohort.status === 'OPEN' && !template.isAutomated && (
                  <button
                    onClick={() => closeCohort(cohort.id)}
                    style={{
                      width: '100%', padding: '10px', borderRadius: 10, background: '#FEF2F2',
                      color: '#DC2626', border: '1px solid #FECACA', fontSize: 12,
                      fontWeight: 700, cursor: 'pointer', display: 'flex',
                      alignItems: 'center', justifyContent: 'center', gap: 6,
                    }}
                  >
                    <Lock size={14} /> Cerrar Grupo
                  </button>
                )}
              </div>
            );
          })}

          {cohorts.length === 0 && !loading && (
            <div style={{
              gridColumn: '1 / -1', textAlign: 'center', padding: '60px 20px',
              color: '#94A3B8', fontSize: 14,
            }}>
              No hay grupos creados para este curso.
              {!template.isAutomated && ' Crea uno con el botón "Nuevo Grupo".'}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
