import { NextRequest, NextResponse } from 'next/server';
import { adminAuth, adminDb } from '@/lib/firebase-admin';
import { sanitize } from '@/lib/utils';
import admin from 'firebase-admin';

/**
 * POST /api/admin/cohorts
 * Creates a new cohort for a course template (manual institutions).
 *
 * PUT /api/admin/cohorts
 * Updates an existing cohort.
 *
 * GET /api/admin/cohorts
 * Lists cohorts for a template or institution.
 */

async function verifyAdmin(req: NextRequest) {
  const authHeader = req.headers.get('authorization');
  if (!authHeader?.startsWith('Bearer ')) throw new Error('No autorizado');

  const token = authHeader.split('Bearer ')[1];
  const decoded = await adminAuth.verifyIdToken(token);
  const userSnap = await adminDb.collection('users').doc(decoded.uid).get();

  if (!userSnap.exists) throw new Error('Usuario no encontrado');
  const user = userSnap.data()!;
  if (!['ADMIN', 'SUPER_ADMIN'].includes(user.role)) throw new Error('Acceso denegado');

  return { uid: decoded.uid, user, institutionId: user.institutionId };
}

// ─── GET ─────────────────────────────────────────────────────────────────────

export async function GET(req: NextRequest) {
  try {
    const { institutionId } = await verifyAdmin(req);
    const { searchParams } = new URL(req.url);
    const templateId = searchParams.get('templateId');

    let q = adminDb.collection('cohorts')
      .where('institutionId', '==', institutionId)
      .orderBy('cohortNumber', 'desc');

    if (templateId) {
      q = adminDb.collection('cohorts')
        .where('templateId', '==', templateId)
        .where('institutionId', '==', institutionId)
        .orderBy('cohortNumber', 'desc');
    }

    const snaps = await q.get();

    const cohorts = snaps.docs.map((doc) => {
      const d = doc.data();
      return {
        id: doc.id,
        ...d,
        enrollmentStart: d.enrollmentStart?.toDate?.()?.toISOString() ?? null,
        enrollmentEnd: d.enrollmentEnd?.toDate?.()?.toISOString() ?? null,
        classesStart: d.classesStart?.toDate?.()?.toISOString() ?? null,
        classesEnd: d.classesEnd?.toDate?.()?.toISOString() ?? null,
        createdAt: d.createdAt?.toDate?.()?.toISOString() ?? null,
        closedAt: d.closedAt?.toDate?.()?.toISOString() ?? null,
      };
    });

    return NextResponse.json({ cohorts });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Error interno';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

// ─── POST: Create cohort ─────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const { institutionId } = await verifyAdmin(req);
    const body = await req.json();

    const templateId = sanitize(body.templateId);
    if (!templateId) {
      return NextResponse.json({ error: 'templateId requerido' }, { status: 400 });
    }

    // Verify template ownership
    const templateSnap = await adminDb.collection('course_templates').doc(templateId).get();
    if (!templateSnap.exists) {
      return NextResponse.json({ error: 'Template no encontrado' }, { status: 404 });
    }
    if (templateSnap.data()?.institutionId !== institutionId) {
      return NextResponse.json({ error: 'No tienes permisos' }, { status: 403 });
    }

    const template = templateSnap.data()!;

    // Get next cohort number
    const lastCohortSnap = await adminDb.collection('cohorts')
      .where('templateId', '==', templateId)
      .orderBy('cohortNumber', 'desc')
      .limit(1)
      .get();

    const nextNumber = lastCohortSnap.empty ? 1 : (lastCohortSnap.docs[0].data().cohortNumber || 0) + 1;

const cohortData = {
      templateId,
      institutionId,
      courseSlug: template.slug,
      courseTitle: template.title,
      cohortNumber: nextNumber,
      scheduleLabel: sanitize(body.scheduleLabel) || 'Horario por definir',
      enrollmentStart: body.enrollmentStart
        ? admin.firestore.Timestamp.fromDate(new Date(body.enrollmentStart))
        : admin.firestore.FieldValue.serverTimestamp(),
      enrollmentEnd: body.enrollmentEnd
        ? admin.firestore.Timestamp.fromDate(new Date(body.enrollmentEnd))
        : admin.firestore.Timestamp.fromDate(new Date(Date.now() + 21 * 24 * 60 * 60 * 1000)),
      classesStart: body.classesStart
        ? admin.firestore.Timestamp.fromDate(new Date(body.classesStart))
        : admin.firestore.FieldValue.serverTimestamp(),
      maxStudents: Number(body.maxStudents) || 30,
      enrolledCount: 0,
      priceCOP: Number(body.priceCOP) || template.priceCOP,
      priceUSD: Number(body.priceUSD) || template.priceUSD,
      status: body.status || 'OPEN',
      isAutoGenerated: false,
      parentCohortId: null,
      instructorIds: Array.isArray(body.instructorIds) ? body.instructorIds : [],
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      closedAt: null,
    };

    const ref = adminDb.collection('cohorts').doc();
    await ref.set(cohortData);

    return NextResponse.json({
      success: true,
      cohortId: ref.id,
      cohortNumber: nextNumber,
      message: `Grupo #${nextNumber} creado para "${template.title}"`,
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Error interno';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

// ─── PUT: Update cohort ──────────────────────────────────────────────────────

export async function PUT(req: NextRequest) {
  try {
    const { institutionId } = await verifyAdmin(req);
    const body = await req.json();

    const cohortId = sanitize(body.id);
    if (!cohortId) {
      return NextResponse.json({ error: 'ID del grupo requerido' }, { status: 400 });
    }

    const cohortSnap = await adminDb.collection('cohorts').doc(cohortId).get();
    if (!cohortSnap.exists) {
      return NextResponse.json({ error: 'Grupo no encontrado' }, { status: 404 });
    }
    if (cohortSnap.data()?.institutionId !== institutionId) {
      return NextResponse.json({ error: 'No tienes permisos' }, { status: 403 });
    }

    const updateData: Record<string, any> = {
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    };

    if (body.scheduleLabel) updateData.scheduleLabel = sanitize(body.scheduleLabel);
    if (body.maxStudents) updateData.maxStudents = Number(body.maxStudents);
    if (body.priceCOP !== undefined) updateData.priceCOP = Number(body.priceCOP);
    if (body.priceUSD !== undefined) updateData.priceUSD = Number(body.priceUSD);
    if (body.status) updateData.status = body.status;
    if (body.enrollmentStart) updateData.enrollmentStart = admin.firestore.Timestamp.fromDate(new Date(body.enrollmentStart));
    if (body.enrollmentEnd) updateData.enrollmentEnd = admin.firestore.Timestamp.fromDate(new Date(body.enrollmentEnd));
    if (body.classesStart) updateData.classesStart = admin.firestore.Timestamp.fromDate(new Date(body.classesStart));

    if (body.status === 'CLOSED' || body.status === 'COMPLETED') {
      updateData.closedAt = admin.firestore.FieldValue.serverTimestamp();
    }

    await adminDb.collection('cohorts').doc(cohortId).update(updateData);

    return NextResponse.json({ success: true, message: 'Grupo actualizado exitosamente' });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Error interno';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
