import { Timestamp } from 'firebase/firestore';

// ─── Cohort Status ───────────────────────────────────────────────────────────

export type CohortStatus =
  | 'UPCOMING'       // Enrollment hasn't started yet
  | 'OPEN'           // Accepting enrollments
  | 'FULL'           // maxStudents reached, no more enrollments
  | 'IN_PROGRESS'    // Classes have started
  | 'CLOSED'         // Manually closed by admin
  | 'COMPLETED';     // Course cycle finished

// ─── Cohort (Group Instance) ─────────────────────────────────────────────────

export interface Cohort {
  id: string;
  templateId: string;
  institutionId: string;

  // Denormalized for fast queries (avoids joins in NoSQL)
  courseSlug: string;
  courseTitle: string;

  cohortNumber: number;
  scheduleLabel: string;

  // ─── Dates ─────────────────────────────────────────────────────────────────
  enrollmentStart: Date | Timestamp;
  enrollmentEnd: Date | Timestamp;
  classesStart: Date | Timestamp;
  classesEnd?: Date | Timestamp;

  // ─── Capacity ──────────────────────────────────────────────────────────────
  maxStudents: number;
  enrolledCount: number;           // Atomic increment via FieldValue.increment()

  // ─── Pricing snapshot (can differ between cohorts) ─────────────────────────
  priceCOP: number;
  priceUSD: number;

  // ─── Status & Lifecycle ────────────────────────────────────────────────────
  status: CohortStatus;
  isAutoGenerated: boolean;
  parentCohortId: string | null;

  // ─── Metadata ──────────────────────────────────────────────────────────────
  instructorIds: string[];
  createdAt: Date | Timestamp;
  updatedAt: Date | Timestamp;
  closedAt?: Date | Timestamp | null;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function isCohortEnrollable(cohort: Cohort): boolean {
  return cohort.status === 'OPEN' && cohort.enrolledCount < cohort.maxStudents;
}

export function getCohortStatusLabel(status: CohortStatus): string {
  const labels: Record<CohortStatus, string> = {
    UPCOMING: 'Próximo',
    OPEN: 'Inscripciones Abiertas',
    FULL: 'Cupos Agotados',
    IN_PROGRESS: 'En Curso',
    CLOSED: 'Cerrado',
    COMPLETED: 'Finalizado',
  };
  return labels[status];
}

export function getCohortStatusColor(status: CohortStatus): string {
  const colors: Record<CohortStatus, string> = {
    UPCOMING: '#6366F1',
    OPEN: '#10B981',
    FULL: '#F59E0B',
    IN_PROGRESS: '#3B82F6',
    CLOSED: '#6B7280',
    COMPLETED: '#8B5CF6',
  };
  return colors[status];
}
